name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    steps:
      - name: Configure
        if: matrix.os == 'windows'
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Linux
        if: matrix.os == 'ubuntu'
        run: ./ci/linux
      - name: Build Windows
        if: matrix.os == 'windows'
        shell: bash
        run: ./ci/windows
